sudo: required
language: python
services:
  - docker
branches:
    - master
before_install:
  - docker pull numix-core/numix-core-devel
script:
    - sh ./tests/pycodestyle.sh
    - python3 ./tests/schema.py
    - python3 ./tests/db_entry.py
    - python3 ./tests/icons_entry.py
    - python3 ./tests/ordered_db.py
